// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyepdduubmobmvunlefm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5ZXBkZHV1Ym1vYm12dW5sZWZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMjQ1NjEsImV4cCI6MjA1OTYwMDU2MX0.SE9aEFnP5vfaVosLfj_OCsKPmgNtdNizcbUOvmpy4zc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);